// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: translator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event Severity
type Severity int32

const (
	Severity_INFO     Severity = 0
	Severity_WARNING  Severity = 1
	Severity_ERROR    Severity = 2
	Severity_CRITICAL Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "ERROR",
		3: "CRITICAL",
	}
	Severity_value = map[string]int32{
		"INFO":     0,
		"WARNING":  1,
		"ERROR":    2,
		"CRITICAL": 3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_translator_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_translator_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{0}
}

// Translation Request
type TranslationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InputFile      string                 `protobuf:"bytes,2,opt,name=input_file,json=inputFile,proto3" json:"input_file,omitempty"`
	OutputFile     string                 `protobuf:"bytes,3,opt,name=output_file,json=outputFile,proto3" json:"output_file,omitempty"`
	SourceLang     string                 `protobuf:"bytes,4,opt,name=source_lang,json=sourceLang,proto3" json:"source_lang,omitempty"`
	TargetLang     string                 `protobuf:"bytes,5,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`
	Script         string                 `protobuf:"bytes,6,opt,name=script,proto3" json:"script,omitempty"` // cyrillic, latin
	ProviderConfig *ProviderConfig        `protobuf:"bytes,7,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	Options        *TranslationOptions    `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClientId       string                 `protobuf:"bytes,10,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslationRequest) Reset() {
	*x = TranslationRequest{}
	mi := &file_translator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationRequest) ProtoMessage() {}

func (x *TranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationRequest.ProtoReflect.Descriptor instead.
func (*TranslationRequest) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{0}
}

func (x *TranslationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranslationRequest) GetInputFile() string {
	if x != nil {
		return x.InputFile
	}
	return ""
}

func (x *TranslationRequest) GetOutputFile() string {
	if x != nil {
		return x.OutputFile
	}
	return ""
}

func (x *TranslationRequest) GetSourceLang() string {
	if x != nil {
		return x.SourceLang
	}
	return ""
}

func (x *TranslationRequest) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

func (x *TranslationRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *TranslationRequest) GetProviderConfig() *ProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *TranslationRequest) GetOptions() *TranslationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TranslationRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TranslationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Provider Configuration
type ProviderConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // openai, anthropic, zhipu, deepseek, qwen, gemini, llamacpp, ssh
	Model          string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Temperature    float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens      int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// API Configuration
	ApiKey  string `protobuf:"bytes,6,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl string `protobuf:"bytes,7,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// SSH Configuration
	SshHost     string `protobuf:"bytes,8,opt,name=ssh_host,json=sshHost,proto3" json:"ssh_host,omitempty"`
	SshUser     string `protobuf:"bytes,9,opt,name=ssh_user,json=sshUser,proto3" json:"ssh_user,omitempty"`
	SshPassword string `protobuf:"bytes,10,opt,name=ssh_password,json=sshPassword,proto3" json:"ssh_password,omitempty"`
	SshPort     int32  `protobuf:"varint,11,opt,name=ssh_port,json=sshPort,proto3" json:"ssh_port,omitempty"`
	RemoteDir   string `protobuf:"bytes,12,opt,name=remote_dir,json=remoteDir,proto3" json:"remote_dir,omitempty"`
	// Llama.cpp Configuration
	LlamaBinary string `protobuf:"bytes,13,opt,name=llama_binary,json=llamaBinary,proto3" json:"llama_binary,omitempty"`
	LlamaModel  string `protobuf:"bytes,14,opt,name=llama_model,json=llamaModel,proto3" json:"llama_model,omitempty"`
	ContextSize int32  `protobuf:"varint,15,opt,name=context_size,json=contextSize,proto3" json:"context_size,omitempty"`
	// Additional options
	AdditionalOptions map[string]string `protobuf:"bytes,16,rep,name=additional_options,json=additionalOptions,proto3" json:"additional_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	mi := &file_translator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProviderConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProviderConfig) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ProviderConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ProviderConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ProviderConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ProviderConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ProviderConfig) GetSshHost() string {
	if x != nil {
		return x.SshHost
	}
	return ""
}

func (x *ProviderConfig) GetSshUser() string {
	if x != nil {
		return x.SshUser
	}
	return ""
}

func (x *ProviderConfig) GetSshPassword() string {
	if x != nil {
		return x.SshPassword
	}
	return ""
}

func (x *ProviderConfig) GetSshPort() int32 {
	if x != nil {
		return x.SshPort
	}
	return 0
}

func (x *ProviderConfig) GetRemoteDir() string {
	if x != nil {
		return x.RemoteDir
	}
	return ""
}

func (x *ProviderConfig) GetLlamaBinary() string {
	if x != nil {
		return x.LlamaBinary
	}
	return ""
}

func (x *ProviderConfig) GetLlamaModel() string {
	if x != nil {
		return x.LlamaModel
	}
	return ""
}

func (x *ProviderConfig) GetContextSize() int32 {
	if x != nil {
		return x.ContextSize
	}
	return 0
}

func (x *ProviderConfig) GetAdditionalOptions() map[string]string {
	if x != nil {
		return x.AdditionalOptions
	}
	return nil
}

// Translation Options
type TranslationOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Workers          int32                  `protobuf:"varint,1,opt,name=workers,proto3" json:"workers,omitempty"`
	ChunkSize        int32                  `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Concurrency      int32                  `protobuf:"varint,3,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	VerifyOutput     bool                   `protobuf:"varint,4,opt,name=verify_output,json=verifyOutput,proto3" json:"verify_output,omitempty"`
	Verbose          bool                   `protobuf:"varint,5,opt,name=verbose,proto3" json:"verbose,omitempty"`
	EnableMonitoring bool                   `protobuf:"varint,6,opt,name=enable_monitoring,json=enableMonitoring,proto3" json:"enable_monitoring,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TranslationOptions) Reset() {
	*x = TranslationOptions{}
	mi := &file_translator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationOptions) ProtoMessage() {}

func (x *TranslationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationOptions.ProtoReflect.Descriptor instead.
func (*TranslationOptions) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{2}
}

func (x *TranslationOptions) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *TranslationOptions) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *TranslationOptions) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *TranslationOptions) GetVerifyOutput() bool {
	if x != nil {
		return x.VerifyOutput
	}
	return false
}

func (x *TranslationOptions) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *TranslationOptions) GetEnableMonitoring() bool {
	if x != nil {
		return x.EnableMonitoring
	}
	return false
}

// Translation Response
type TranslationResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SessionId                string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status                   string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // started, queued, error
	Message                  string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	StartedAt                *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EstimatedDurationSeconds int32                  `protobuf:"varint,5,opt,name=estimated_duration_seconds,json=estimatedDurationSeconds,proto3" json:"estimated_duration_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TranslationResponse) Reset() {
	*x = TranslationResponse{}
	mi := &file_translator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationResponse) ProtoMessage() {}

func (x *TranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationResponse.ProtoReflect.Descriptor instead.
func (*TranslationResponse) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{3}
}

func (x *TranslationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranslationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TranslationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TranslationResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TranslationResponse) GetEstimatedDurationSeconds() int32 {
	if x != nil {
		return x.EstimatedDurationSeconds
	}
	return 0
}

// Translation Status Request
type TranslationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationStatusRequest) Reset() {
	*x = TranslationStatusRequest{}
	mi := &file_translator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationStatusRequest) ProtoMessage() {}

func (x *TranslationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationStatusRequest.ProtoReflect.Descriptor instead.
func (*TranslationStatusRequest) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{4}
}

func (x *TranslationStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Translation Status Response
type TranslationStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // pending, running, completed, failed, cancelled
	ProgressPercentage  float64                `protobuf:"fixed64,3,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	CurrentStep         string                 `protobuf:"bytes,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Message             string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	StartedAt           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EstimatedCompletion *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"`
	Files               []*GeneratedFile       `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`
	Steps               []*TranslationStep     `protobuf:"bytes,10,rep,name=steps,proto3" json:"steps,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode           int32                  `protobuf:"varint,12,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TranslationStatusResponse) Reset() {
	*x = TranslationStatusResponse{}
	mi := &file_translator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationStatusResponse) ProtoMessage() {}

func (x *TranslationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationStatusResponse.ProtoReflect.Descriptor instead.
func (*TranslationStatusResponse) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{5}
}

func (x *TranslationStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranslationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TranslationStatusResponse) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *TranslationStatusResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *TranslationStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TranslationStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TranslationStatusResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TranslationStatusResponse) GetEstimatedCompletion() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedCompletion
	}
	return nil
}

func (x *TranslationStatusResponse) GetFiles() []*GeneratedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *TranslationStatusResponse) GetSteps() []*TranslationStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *TranslationStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TranslationStatusResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

// Translation List Response
type TranslationListResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Translations  []*TranslationStatusResponse `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty"`
	TotalCount    int32                        `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationListResponse) Reset() {
	*x = TranslationListResponse{}
	mi := &file_translator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationListResponse) ProtoMessage() {}

func (x *TranslationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationListResponse.ProtoReflect.Descriptor instead.
func (*TranslationListResponse) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{6}
}

func (x *TranslationListResponse) GetTranslations() []*TranslationStatusResponse {
	if x != nil {
		return x.Translations
	}
	return nil
}

func (x *TranslationListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Cancel Translation Request
type CancelTranslationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTranslationRequest) Reset() {
	*x = CancelTranslationRequest{}
	mi := &file_translator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTranslationRequest) ProtoMessage() {}

func (x *CancelTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTranslationRequest.ProtoReflect.Descriptor instead.
func (*CancelTranslationRequest) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTranslationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CancelTranslationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Cancel Translation Response
type CancelTranslationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTranslationResponse) Reset() {
	*x = CancelTranslationResponse{}
	mi := &file_translator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTranslationResponse) ProtoMessage() {}

func (x *CancelTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTranslationResponse.ProtoReflect.Descriptor instead.
func (*CancelTranslationResponse) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTranslationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CancelTranslationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTranslationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Translation Stream Request
type TranslationStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationStreamRequest) Reset() {
	*x = TranslationStreamRequest{}
	mi := &file_translator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationStreamRequest) ProtoMessage() {}

func (x *TranslationStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationStreamRequest.ProtoReflect.Descriptor instead.
func (*TranslationStreamRequest) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{9}
}

func (x *TranslationStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranslationStreamRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Translation Progress Event
type TranslationProgressEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType          string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // step_started, step_completed, progress_update, error, completed
	StepName           string                 `protobuf:"bytes,3,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	ProgressPercentage float64                `protobuf:"fixed64,4,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	Message            string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Step-specific data
	CurrentItem      int32  `protobuf:"varint,8,opt,name=current_item,json=currentItem,proto3" json:"current_item,omitempty"`
	TotalItems       int32  `protobuf:"varint,9,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	CurrentOperation string `protobuf:"bytes,10,opt,name=current_operation,json=currentOperation,proto3" json:"current_operation,omitempty"`
	// Error information
	ErrorMessage  string `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     int32  `protobuf:"varint,12,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	IsRecoverable bool   `protobuf:"varint,13,opt,name=is_recoverable,json=isRecoverable,proto3" json:"is_recoverable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationProgressEvent) Reset() {
	*x = TranslationProgressEvent{}
	mi := &file_translator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationProgressEvent) ProtoMessage() {}

func (x *TranslationProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationProgressEvent.ProtoReflect.Descriptor instead.
func (*TranslationProgressEvent) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{10}
}

func (x *TranslationProgressEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranslationProgressEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TranslationProgressEvent) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *TranslationProgressEvent) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *TranslationProgressEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TranslationProgressEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TranslationProgressEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TranslationProgressEvent) GetCurrentItem() int32 {
	if x != nil {
		return x.CurrentItem
	}
	return 0
}

func (x *TranslationProgressEvent) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *TranslationProgressEvent) GetCurrentOperation() string {
	if x != nil {
		return x.CurrentOperation
	}
	return ""
}

func (x *TranslationProgressEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TranslationProgressEvent) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *TranslationProgressEvent) GetIsRecoverable() bool {
	if x != nil {
		return x.IsRecoverable
	}
	return false
}

// Generated File Information
type GeneratedFile struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Path                string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type                string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // original_md, translated_md, epub, report
	Size                int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ContentType         string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Verified            bool                   `protobuf:"varint,5,opt,name=verified,proto3" json:"verified,omitempty"`
	VerificationMessage string                 `protobuf:"bytes,6,opt,name=verification_message,json=verificationMessage,proto3" json:"verification_message,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GeneratedFile) Reset() {
	*x = GeneratedFile{}
	mi := &file_translator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedFile) ProtoMessage() {}

func (x *GeneratedFile) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedFile.ProtoReflect.Descriptor instead.
func (*GeneratedFile) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{11}
}

func (x *GeneratedFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GeneratedFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GeneratedFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GeneratedFile) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GeneratedFile) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *GeneratedFile) GetVerificationMessage() string {
	if x != nil {
		return x.VerificationMessage
	}
	return ""
}

func (x *GeneratedFile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Translation Step Information
type TranslationStep struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // pending, running, completed, failed
	StartedAt          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	ProgressPercentage float64                `protobuf:"fixed64,5,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	Message            string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TranslationStep) Reset() {
	*x = TranslationStep{}
	mi := &file_translator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationStep) ProtoMessage() {}

func (x *TranslationStep) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationStep.ProtoReflect.Descriptor instead.
func (*TranslationStep) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{12}
}

func (x *TranslationStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TranslationStep) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TranslationStep) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TranslationStep) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *TranslationStep) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *TranslationStep) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TranslationStep) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Providers Response
type ProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvidersResponse) Reset() {
	*x = ProvidersResponse{}
	mi := &file_translator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvidersResponse) ProtoMessage() {}

func (x *ProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvidersResponse.ProtoReflect.Descriptor instead.
func (*ProvidersResponse) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{13}
}

func (x *ProvidersResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

// Provider Information
type ProviderInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AvailableModels     []string               `protobuf:"bytes,4,rep,name=available_models,json=availableModels,proto3" json:"available_models,omitempty"`
	Capabilities        map[string]string      `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequiresApiKey      bool                   `protobuf:"varint,6,opt,name=requires_api_key,json=requiresApiKey,proto3" json:"requires_api_key,omitempty"`
	RequiresSshConfig   bool                   `protobuf:"varint,7,opt,name=requires_ssh_config,json=requiresSshConfig,proto3" json:"requires_ssh_config,omitempty"`
	RequiresLocalBinary bool                   `protobuf:"varint,8,opt,name=requires_local_binary,json=requiresLocalBinary,proto3" json:"requires_local_binary,omitempty"`
	Status              *ProviderStatus        `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_translator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{14}
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProviderInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProviderInfo) GetAvailableModels() []string {
	if x != nil {
		return x.AvailableModels
	}
	return nil
}

func (x *ProviderInfo) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderInfo) GetRequiresApiKey() bool {
	if x != nil {
		return x.RequiresApiKey
	}
	return false
}

func (x *ProviderInfo) GetRequiresSshConfig() bool {
	if x != nil {
		return x.RequiresSshConfig
	}
	return false
}

func (x *ProviderInfo) GetRequiresLocalBinary() bool {
	if x != nil {
		return x.RequiresLocalBinary
	}
	return false
}

func (x *ProviderInfo) GetStatus() *ProviderStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Provider Status
type ProviderStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Available      bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	StatusMessage  string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	LastChecked    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	ResponseTimeMs float64                `protobuf:"fixed64,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderStatus) Reset() {
	*x = ProviderStatus{}
	mi := &file_translator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatus) ProtoMessage() {}

func (x *ProviderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatus.ProtoReflect.Descriptor instead.
func (*ProviderStatus) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{15}
}

func (x *ProviderStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ProviderStatus) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *ProviderStatus) GetLastChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChecked
	}
	return nil
}

func (x *ProviderStatus) GetResponseTimeMs() float64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

// Event Subscription Request
type EventSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`                                                   // If empty, subscribe to all events
	Filters       map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional filters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSubscriptionRequest) Reset() {
	*x = EventSubscriptionRequest{}
	mi := &file_translator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscriptionRequest) ProtoMessage() {}

func (x *EventSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*EventSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{16}
}

func (x *EventSubscriptionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *EventSubscriptionRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *EventSubscriptionRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

// System Event
type SystemEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Severity      Severity               `protobuf:"varint,7,opt,name=severity,proto3,enum=translator.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemEvent) Reset() {
	*x = SystemEvent{}
	mi := &file_translator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEvent) ProtoMessage() {}

func (x *SystemEvent) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEvent.ProtoReflect.Descriptor instead.
func (*SystemEvent) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{17}
}

func (x *SystemEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SystemEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SystemEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SystemEvent) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SystemEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SystemEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SystemEvent) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_INFO
}

var File_translator_proto protoreflect.FileDescriptor

const file_translator_proto_rawDesc = "" +
	"\n" +
	"\x10translator.proto\x12\n" +
	"translator\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa4\x03\n" +
	"\x12TranslationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"input_file\x18\x02 \x01(\tR\tinputFile\x12\x1f\n" +
	"\voutput_file\x18\x03 \x01(\tR\n" +
	"outputFile\x12\x1f\n" +
	"\vsource_lang\x18\x04 \x01(\tR\n" +
	"sourceLang\x12\x1f\n" +
	"\vtarget_lang\x18\x05 \x01(\tR\n" +
	"targetLang\x12\x16\n" +
	"\x06script\x18\x06 \x01(\tR\x06script\x12C\n" +
	"\x0fprovider_config\x18\a \x01(\v2\x1a.translator.ProviderConfigR\x0eproviderConfig\x128\n" +
	"\aoptions\x18\b \x01(\v2\x1e.translator.TranslationOptionsR\aoptions\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tclient_id\x18\n" +
	" \x01(\tR\bclientId\"\xfa\x04\n" +
	"\x0eProviderConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x17\n" +
	"\aapi_key\x18\x06 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\a \x01(\tR\abaseUrl\x12\x19\n" +
	"\bssh_host\x18\b \x01(\tR\asshHost\x12\x19\n" +
	"\bssh_user\x18\t \x01(\tR\asshUser\x12!\n" +
	"\fssh_password\x18\n" +
	" \x01(\tR\vsshPassword\x12\x19\n" +
	"\bssh_port\x18\v \x01(\x05R\asshPort\x12\x1d\n" +
	"\n" +
	"remote_dir\x18\f \x01(\tR\tremoteDir\x12!\n" +
	"\fllama_binary\x18\r \x01(\tR\vllamaBinary\x12\x1f\n" +
	"\vllama_model\x18\x0e \x01(\tR\n" +
	"llamaModel\x12!\n" +
	"\fcontext_size\x18\x0f \x01(\x05R\vcontextSize\x12`\n" +
	"\x12additional_options\x18\x10 \x03(\v21.translator.ProviderConfig.AdditionalOptionsEntryR\x11additionalOptions\x1aD\n" +
	"\x16AdditionalOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x12TranslationOptions\x12\x18\n" +
	"\aworkers\x18\x01 \x01(\x05R\aworkers\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\x05R\tchunkSize\x12 \n" +
	"\vconcurrency\x18\x03 \x01(\x05R\vconcurrency\x12#\n" +
	"\rverify_output\x18\x04 \x01(\bR\fverifyOutput\x12\x18\n" +
	"\averbose\x18\x05 \x01(\bR\averbose\x12+\n" +
	"\x11enable_monitoring\x18\x06 \x01(\bR\x10enableMonitoring\"\xdf\x01\n" +
	"\x13TranslationResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12<\n" +
	"\x1aestimated_duration_seconds\x18\x05 \x01(\x05R\x18estimatedDurationSeconds\"9\n" +
	"\x18TranslationStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xad\x04\n" +
	"\x19TranslationStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12/\n" +
	"\x13progress_percentage\x18\x03 \x01(\x01R\x12progressPercentage\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\tR\vcurrentStep\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12M\n" +
	"\x14estimated_completion\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x13estimatedCompletion\x12/\n" +
	"\x05files\x18\t \x03(\v2\x19.translator.GeneratedFileR\x05files\x121\n" +
	"\x05steps\x18\n" +
	" \x03(\v2\x1b.translator.TranslationStepR\x05steps\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\f \x01(\x05R\terrorCode\"\x85\x01\n" +
	"\x17TranslationListResponse\x12I\n" +
	"\ftranslations\x18\x01 \x03(\v2%.translator.TranslationStatusResponseR\ftranslations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"Q\n" +
	"\x18CancelTranslationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"n\n" +
	"\x19CancelTranslationResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"V\n" +
	"\x18TranslationStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\xe3\x04\n" +
	"\x18TranslationProgressEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1b\n" +
	"\tstep_name\x18\x03 \x01(\tR\bstepName\x12/\n" +
	"\x13progress_percentage\x18\x04 \x01(\x01R\x12progressPercentage\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12N\n" +
	"\bmetadata\x18\x06 \x03(\v22.translator.TranslationProgressEvent.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fcurrent_item\x18\b \x01(\x05R\vcurrentItem\x12\x1f\n" +
	"\vtotal_items\x18\t \x01(\x05R\n" +
	"totalItems\x12+\n" +
	"\x11current_operation\x18\n" +
	" \x01(\tR\x10currentOperation\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\f \x01(\x05R\terrorCode\x12%\n" +
	"\x0eis_recoverable\x18\r \x01(\bR\risRecoverable\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x01\n" +
	"\rGeneratedFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bverified\x18\x05 \x01(\bR\bverified\x121\n" +
	"\x14verification_message\x18\x06 \x01(\tR\x13verificationMessage\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9f\x02\n" +
	"\x0fTranslationStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12/\n" +
	"\x13progress_percentage\x18\x05 \x01(\x01R\x12progressPercentage\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"K\n" +
	"\x11ProvidersResponse\x126\n" +
	"\tproviders\x18\x01 \x03(\v2\x18.translator.ProviderInfoR\tproviders\"\xd6\x03\n" +
	"\fProviderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10available_models\x18\x04 \x03(\tR\x0favailableModels\x12N\n" +
	"\fcapabilities\x18\x05 \x03(\v2*.translator.ProviderInfo.CapabilitiesEntryR\fcapabilities\x12(\n" +
	"\x10requires_api_key\x18\x06 \x01(\bR\x0erequiresApiKey\x12.\n" +
	"\x13requires_ssh_config\x18\a \x01(\bR\x11requiresSshConfig\x122\n" +
	"\x15requires_local_binary\x18\b \x01(\bR\x13requiresLocalBinary\x122\n" +
	"\x06status\x18\t \x01(\v2\x1a.translator.ProviderStatusR\x06status\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x0eProviderStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12=\n" +
	"\flast_checked\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastChecked\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x01R\x0eresponseTimeMs\"\xe1\x01\n" +
	"\x18EventSubscriptionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\x12K\n" +
	"\afilters\x18\x03 \x03(\v21.translator.EventSubscriptionRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x02\n" +
	"\vSystemEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\x04data\x18\x04 \x03(\v2!.translator.SystemEvent.DataEntryR\x04data\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x120\n" +
	"\bseverity\x18\a \x01(\x0e2\x14.translator.SeverityR\bseverity\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*:\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x032\x87\x05\n" +
	"\x12TranslationService\x12S\n" +
	"\x10StartTranslation\x12\x1e.translator.TranslationRequest\x1a\x1f.translator.TranslationResponse\x12c\n" +
	"\x14GetTranslationStatus\x12$.translator.TranslationStatusRequest\x1a%.translator.TranslationStatusResponse\x12O\n" +
	"\x10ListTranslations\x12\x16.google.protobuf.Empty\x1a#.translator.TranslationListResponse\x12`\n" +
	"\x11CancelTranslation\x12$.translator.CancelTranslationRequest\x1a%.translator.CancelTranslationResponse\x12i\n" +
	"\x19StreamTranslationProgress\x12$.translator.TranslationStreamRequest\x1a$.translator.TranslationProgressEvent0\x01\x12E\n" +
	"\fGetProviders\x12\x16.google.protobuf.Empty\x1a\x1d.translator.ProvidersResponse\x12R\n" +
	"\x0fSubscribeEvents\x12$.translator.EventSubscriptionRequest\x1a\x17.translator.SystemEvent0\x01B#Z!digital.vasic.translator/pkg/grpcb\x06proto3"

var (
	file_translator_proto_rawDescOnce sync.Once
	file_translator_proto_rawDescData []byte
)

func file_translator_proto_rawDescGZIP() []byte {
	file_translator_proto_rawDescOnce.Do(func() {
		file_translator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translator_proto_rawDesc), len(file_translator_proto_rawDesc)))
	})
	return file_translator_proto_rawDescData
}

var file_translator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_translator_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_translator_proto_goTypes = []any{
	(Severity)(0),                     // 0: translator.Severity
	(*TranslationRequest)(nil),        // 1: translator.TranslationRequest
	(*ProviderConfig)(nil),            // 2: translator.ProviderConfig
	(*TranslationOptions)(nil),        // 3: translator.TranslationOptions
	(*TranslationResponse)(nil),       // 4: translator.TranslationResponse
	(*TranslationStatusRequest)(nil),  // 5: translator.TranslationStatusRequest
	(*TranslationStatusResponse)(nil), // 6: translator.TranslationStatusResponse
	(*TranslationListResponse)(nil),   // 7: translator.TranslationListResponse
	(*CancelTranslationRequest)(nil),  // 8: translator.CancelTranslationRequest
	(*CancelTranslationResponse)(nil), // 9: translator.CancelTranslationResponse
	(*TranslationStreamRequest)(nil),  // 10: translator.TranslationStreamRequest
	(*TranslationProgressEvent)(nil),  // 11: translator.TranslationProgressEvent
	(*GeneratedFile)(nil),             // 12: translator.GeneratedFile
	(*TranslationStep)(nil),           // 13: translator.TranslationStep
	(*ProvidersResponse)(nil),         // 14: translator.ProvidersResponse
	(*ProviderInfo)(nil),              // 15: translator.ProviderInfo
	(*ProviderStatus)(nil),            // 16: translator.ProviderStatus
	(*EventSubscriptionRequest)(nil),  // 17: translator.EventSubscriptionRequest
	(*SystemEvent)(nil),               // 18: translator.SystemEvent
	nil,                               // 19: translator.ProviderConfig.AdditionalOptionsEntry
	nil,                               // 20: translator.TranslationProgressEvent.MetadataEntry
	nil,                               // 21: translator.ProviderInfo.CapabilitiesEntry
	nil,                               // 22: translator.EventSubscriptionRequest.FiltersEntry
	nil,                               // 23: translator.SystemEvent.DataEntry
	(*timestamppb.Timestamp)(nil),     // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 25: google.protobuf.Empty
}
var file_translator_proto_depIdxs = []int32{
	2,  // 0: translator.TranslationRequest.provider_config:type_name -> translator.ProviderConfig
	3,  // 1: translator.TranslationRequest.options:type_name -> translator.TranslationOptions
	24, // 2: translator.TranslationRequest.created_at:type_name -> google.protobuf.Timestamp
	19, // 3: translator.ProviderConfig.additional_options:type_name -> translator.ProviderConfig.AdditionalOptionsEntry
	24, // 4: translator.TranslationResponse.started_at:type_name -> google.protobuf.Timestamp
	24, // 5: translator.TranslationStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	24, // 6: translator.TranslationStatusResponse.updated_at:type_name -> google.protobuf.Timestamp
	24, // 7: translator.TranslationStatusResponse.estimated_completion:type_name -> google.protobuf.Timestamp
	12, // 8: translator.TranslationStatusResponse.files:type_name -> translator.GeneratedFile
	13, // 9: translator.TranslationStatusResponse.steps:type_name -> translator.TranslationStep
	6,  // 10: translator.TranslationListResponse.translations:type_name -> translator.TranslationStatusResponse
	20, // 11: translator.TranslationProgressEvent.metadata:type_name -> translator.TranslationProgressEvent.MetadataEntry
	24, // 12: translator.TranslationProgressEvent.timestamp:type_name -> google.protobuf.Timestamp
	24, // 13: translator.GeneratedFile.created_at:type_name -> google.protobuf.Timestamp
	24, // 14: translator.TranslationStep.started_at:type_name -> google.protobuf.Timestamp
	24, // 15: translator.TranslationStep.ended_at:type_name -> google.protobuf.Timestamp
	15, // 16: translator.ProvidersResponse.providers:type_name -> translator.ProviderInfo
	21, // 17: translator.ProviderInfo.capabilities:type_name -> translator.ProviderInfo.CapabilitiesEntry
	16, // 18: translator.ProviderInfo.status:type_name -> translator.ProviderStatus
	24, // 19: translator.ProviderStatus.last_checked:type_name -> google.protobuf.Timestamp
	22, // 20: translator.EventSubscriptionRequest.filters:type_name -> translator.EventSubscriptionRequest.FiltersEntry
	24, // 21: translator.SystemEvent.timestamp:type_name -> google.protobuf.Timestamp
	23, // 22: translator.SystemEvent.data:type_name -> translator.SystemEvent.DataEntry
	0,  // 23: translator.SystemEvent.severity:type_name -> translator.Severity
	1,  // 24: translator.TranslationService.StartTranslation:input_type -> translator.TranslationRequest
	5,  // 25: translator.TranslationService.GetTranslationStatus:input_type -> translator.TranslationStatusRequest
	25, // 26: translator.TranslationService.ListTranslations:input_type -> google.protobuf.Empty
	8,  // 27: translator.TranslationService.CancelTranslation:input_type -> translator.CancelTranslationRequest
	10, // 28: translator.TranslationService.StreamTranslationProgress:input_type -> translator.TranslationStreamRequest
	25, // 29: translator.TranslationService.GetProviders:input_type -> google.protobuf.Empty
	17, // 30: translator.TranslationService.SubscribeEvents:input_type -> translator.EventSubscriptionRequest
	4,  // 31: translator.TranslationService.StartTranslation:output_type -> translator.TranslationResponse
	6,  // 32: translator.TranslationService.GetTranslationStatus:output_type -> translator.TranslationStatusResponse
	7,  // 33: translator.TranslationService.ListTranslations:output_type -> translator.TranslationListResponse
	9,  // 34: translator.TranslationService.CancelTranslation:output_type -> translator.CancelTranslationResponse
	11, // 35: translator.TranslationService.StreamTranslationProgress:output_type -> translator.TranslationProgressEvent
	14, // 36: translator.TranslationService.GetProviders:output_type -> translator.ProvidersResponse
	18, // 37: translator.TranslationService.SubscribeEvents:output_type -> translator.SystemEvent
	31, // [31:38] is the sub-list for method output_type
	24, // [24:31] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_translator_proto_init() }
func file_translator_proto_init() {
	if File_translator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translator_proto_rawDesc), len(file_translator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translator_proto_goTypes,
		DependencyIndexes: file_translator_proto_depIdxs,
		EnumInfos:         file_translator_proto_enumTypes,
		MessageInfos:      file_translator_proto_msgTypes,
	}.Build()
	File_translator_proto = out.File
	file_translator_proto_goTypes = nil
	file_translator_proto_depIdxs = nil
}
