// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.5
// source: translator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranslationService_StartTranslation_FullMethodName          = "/translator.TranslationService/StartTranslation"
	TranslationService_GetTranslationStatus_FullMethodName      = "/translator.TranslationService/GetTranslationStatus"
	TranslationService_ListTranslations_FullMethodName          = "/translator.TranslationService/ListTranslations"
	TranslationService_CancelTranslation_FullMethodName         = "/translator.TranslationService/CancelTranslation"
	TranslationService_StreamTranslationProgress_FullMethodName = "/translator.TranslationService/StreamTranslationProgress"
	TranslationService_GetProviders_FullMethodName              = "/translator.TranslationService/GetProviders"
	TranslationService_SubscribeEvents_FullMethodName           = "/translator.TranslationService/SubscribeEvents"
)

// TranslationServiceClient is the client API for TranslationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Translation Service Definition
type TranslationServiceClient interface {
	// Start a new translation job
	StartTranslation(ctx context.Context, in *TranslationRequest, opts ...grpc.CallOption) (*TranslationResponse, error)
	// Get translation status
	GetTranslationStatus(ctx context.Context, in *TranslationStatusRequest, opts ...grpc.CallOption) (*TranslationStatusResponse, error)
	// List all translation sessions
	ListTranslations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TranslationListResponse, error)
	// Cancel a translation
	CancelTranslation(ctx context.Context, in *CancelTranslationRequest, opts ...grpc.CallOption) (*CancelTranslationResponse, error)
	// Stream translation progress
	StreamTranslationProgress(ctx context.Context, in *TranslationStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TranslationProgressEvent], error)
	// Get available providers and models
	GetProviders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProvidersResponse, error)
	// Subscribe to system events
	SubscribeEvents(ctx context.Context, in *EventSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemEvent], error)
}

type translationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslationServiceClient(cc grpc.ClientConnInterface) TranslationServiceClient {
	return &translationServiceClient{cc}
}

func (c *translationServiceClient) StartTranslation(ctx context.Context, in *TranslationRequest, opts ...grpc.CallOption) (*TranslationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslationResponse)
	err := c.cc.Invoke(ctx, TranslationService_StartTranslation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) GetTranslationStatus(ctx context.Context, in *TranslationStatusRequest, opts ...grpc.CallOption) (*TranslationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslationStatusResponse)
	err := c.cc.Invoke(ctx, TranslationService_GetTranslationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) ListTranslations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TranslationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslationListResponse)
	err := c.cc.Invoke(ctx, TranslationService_ListTranslations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) CancelTranslation(ctx context.Context, in *CancelTranslationRequest, opts ...grpc.CallOption) (*CancelTranslationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTranslationResponse)
	err := c.cc.Invoke(ctx, TranslationService_CancelTranslation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) StreamTranslationProgress(ctx context.Context, in *TranslationStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TranslationProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranslationService_ServiceDesc.Streams[0], TranslationService_StreamTranslationProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranslationStreamRequest, TranslationProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationService_StreamTranslationProgressClient = grpc.ServerStreamingClient[TranslationProgressEvent]

func (c *translationServiceClient) GetProviders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvidersResponse)
	err := c.cc.Invoke(ctx, TranslationService_GetProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) SubscribeEvents(ctx context.Context, in *EventSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranslationService_ServiceDesc.Streams[1], TranslationService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventSubscriptionRequest, SystemEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationService_SubscribeEventsClient = grpc.ServerStreamingClient[SystemEvent]

// TranslationServiceServer is the server API for TranslationService service.
// All implementations must embed UnimplementedTranslationServiceServer
// for forward compatibility.
//
// Translation Service Definition
type TranslationServiceServer interface {
	// Start a new translation job
	StartTranslation(context.Context, *TranslationRequest) (*TranslationResponse, error)
	// Get translation status
	GetTranslationStatus(context.Context, *TranslationStatusRequest) (*TranslationStatusResponse, error)
	// List all translation sessions
	ListTranslations(context.Context, *emptypb.Empty) (*TranslationListResponse, error)
	// Cancel a translation
	CancelTranslation(context.Context, *CancelTranslationRequest) (*CancelTranslationResponse, error)
	// Stream translation progress
	StreamTranslationProgress(*TranslationStreamRequest, grpc.ServerStreamingServer[TranslationProgressEvent]) error
	// Get available providers and models
	GetProviders(context.Context, *emptypb.Empty) (*ProvidersResponse, error)
	// Subscribe to system events
	SubscribeEvents(*EventSubscriptionRequest, grpc.ServerStreamingServer[SystemEvent]) error
	mustEmbedUnimplementedTranslationServiceServer()
}

// UnimplementedTranslationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranslationServiceServer struct{}

func (UnimplementedTranslationServiceServer) StartTranslation(context.Context, *TranslationRequest) (*TranslationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTranslation not implemented")
}
func (UnimplementedTranslationServiceServer) GetTranslationStatus(context.Context, *TranslationStatusRequest) (*TranslationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTranslationStatus not implemented")
}
func (UnimplementedTranslationServiceServer) ListTranslations(context.Context, *emptypb.Empty) (*TranslationListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTranslations not implemented")
}
func (UnimplementedTranslationServiceServer) CancelTranslation(context.Context, *CancelTranslationRequest) (*CancelTranslationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTranslation not implemented")
}
func (UnimplementedTranslationServiceServer) StreamTranslationProgress(*TranslationStreamRequest, grpc.ServerStreamingServer[TranslationProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamTranslationProgress not implemented")
}
func (UnimplementedTranslationServiceServer) GetProviders(context.Context, *emptypb.Empty) (*ProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedTranslationServiceServer) SubscribeEvents(*EventSubscriptionRequest, grpc.ServerStreamingServer[SystemEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedTranslationServiceServer) mustEmbedUnimplementedTranslationServiceServer() {}
func (UnimplementedTranslationServiceServer) testEmbeddedByValue()                            {}

// UnsafeTranslationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslationServiceServer will
// result in compilation errors.
type UnsafeTranslationServiceServer interface {
	mustEmbedUnimplementedTranslationServiceServer()
}

func RegisterTranslationServiceServer(s grpc.ServiceRegistrar, srv TranslationServiceServer) {
	// If the following call panics, it indicates UnimplementedTranslationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranslationService_ServiceDesc, srv)
}

func _TranslationService_StartTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).StartTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_StartTranslation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).StartTranslation(ctx, req.(*TranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_GetTranslationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).GetTranslationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_GetTranslationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).GetTranslationStatus(ctx, req.(*TranslationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_ListTranslations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).ListTranslations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_ListTranslations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).ListTranslations(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_CancelTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).CancelTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_CancelTranslation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).CancelTranslation(ctx, req.(*CancelTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_StreamTranslationProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TranslationStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TranslationServiceServer).StreamTranslationProgress(m, &grpc.GenericServerStream[TranslationStreamRequest, TranslationProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationService_StreamTranslationProgressServer = grpc.ServerStreamingServer[TranslationProgressEvent]

func _TranslationService_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_GetProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).GetProviders(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventSubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TranslationServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[EventSubscriptionRequest, SystemEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationService_SubscribeEventsServer = grpc.ServerStreamingServer[SystemEvent]

// TranslationService_ServiceDesc is the grpc.ServiceDesc for TranslationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranslationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "translator.TranslationService",
	HandlerType: (*TranslationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartTranslation",
			Handler:    _TranslationService_StartTranslation_Handler,
		},
		{
			MethodName: "GetTranslationStatus",
			Handler:    _TranslationService_GetTranslationStatus_Handler,
		},
		{
			MethodName: "ListTranslations",
			Handler:    _TranslationService_ListTranslations_Handler,
		},
		{
			MethodName: "CancelTranslation",
			Handler:    _TranslationService_CancelTranslation_Handler,
		},
		{
			MethodName: "GetProviders",
			Handler:    _TranslationService_GetProviders_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTranslationProgress",
			Handler:       _TranslationService_StreamTranslationProgress_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeEvents",
			Handler:       _TranslationService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "translator.proto",
}
